spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/invoice_app
    username: postgres
    password: guest

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081